name: cookietemple lint

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v4.3.0
              with:
                  python-version: 3.8

            - name: Install cookietemple
              run: |
                  pip install cookietemple==1.3.5

            - name: Run cookietemple lint
              run: |
                  cookietemple lint . --skip-external
